version: "3.4"
services:
  eventstore:
    build: eventstore/
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/:/opt/elasticsearch/config/
    ports:
      - 9200:9200
  # kibana:
  #   build: kibana/
  #   ports:
  #     - "5601:5601"
  #   volumes:
  #     - ./kibana/config/:/opt/kibana/config/
  #   environment:
  #     ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
volumes:
  esdata:
    driver: local
