version: "3.4"
services:
  client:
    build: client/
    container_name: client
    ports:
      - 8000:80
    networks:
      - esnet
  eventstore:
    image: eventstore/eventstore
    container_name: eventstore
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    command: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - cluster.name=docker-cluster
    networks:
      - esnet
  evt-es-bridge:
    build: dotnet-event-elastic-bridge
    container_name: evt-es-bridge
    environment:
      - STREAM_NAME=analytics
      - STREAM_URL=eventstore
      - ELASTIC_NAME=elasticsearch
      - EVENTSTORE_NAME=eventstore
      - USER=admin
      - PW=changeit
    networks:
      - esnet
volumes:
  elasticdata:
    driver: local
  kibanadata:
    driver: local

networks:
  esnet:
