version: "3.4"
services:
  eventstore:
    build: eventstore/
    ports:
      - "2113:2113"
      - "1113:1113"
  elasticsearch:
    build: elasticsearch/
    command: elasticsearch -Enetwork.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9201:9201"
    volumes:
      - ./elasticsearch/config/:/opt/elasticsearch/config/
  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    environment:
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
